image: node:16.13.0

before_script:
  - npm install

cache:
  paths:
    - node_modules/

pages:
  script:
    - npm run build
    - mv dist public
    - find public \( -name '*.html' -o -name '*.css' -o -name '*.js' \) -print0 | xargs -0 gzip -9 -kv

  artifacts:
    paths:
    - public

  only:
    - main